services:
  - type: web
    name: removedor-fundo
    env: python
    plan: free
    # Modificação aqui: Adicionando o download do modelo do rembg
    buildCommand: |
      pip install -r requirements.txt
      rembg p # Este comando baixa os modelos padrão
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true